apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-sc
provisioner: filestore.csi.storage.gke.io
parameters:
  tier: BASIC_HDD # change this value as needed
  network: default # change this value as needed
  location: us-central1-c # change this value as needed
reclaimPolicy: Retain # change this value as needed
