apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"c1-ingress","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"http":{"paths":[{"backend":{"service":{"name":"a1","port":{"number":80}}},"path":"/apple(/|$)(.*)","pathType":"Prefix"},{"backend":{"service":{"name":"b2","port":{"number":80}}},"path":"/ball(/|$)(.*)","pathType":"Prefix"}]}}]}}
  creationTimestamp: "2023-09-07T07:00:03Z"
  generation: 1
  name: c1-ingress
  namespace: default
  resourceVersion: "34495543"
  uid: fb9456fd-3002-4c0e-9740-fe76e19b4920
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: a1
            port:
              number: 80
        path: /apple(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: b2
            port:
              number: 80
        path: /ball(/|$)(.*)
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 34.30.83.221
