apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deploy1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onedeploy
  template:
    metadata:
      labels:
        app: onedeploy
    spec:
      containers:
      - name: my-conatiner
        image: nginx:latest
        ports:
        - containerPort: 8080
        env:
        - name: TITLE 
          value: "NGINX APP1" 


---
apiVersion: v1
kind: Service
metadata: 
  name: onecluster
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: onedeploy
