apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secdeploy
  template:
    metadata:
      labels:
        app: secdeploy
    spec:
      containers:
      - name: my-secconatiner
        image: yeasy/simple-web
        ports:
        - containerPort: 8080
        env:
        - name: TITLE 
          value: "NGINX APP1" 
 
          
---
apiVersion: v1
kind: Service
metadata:
  name: secclusterip
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: secdeploy

